python main.py test --lang 'bi' --fold 1 --gpu 2 --pt_name 'name_of_your_model_fold1_lang'
python main.py test --lang 'bi' --fold 2 --gpu 2 --pt_name 'name_of_your_model_fold2_lang'
python main.py test --lang 'bi' --fold 3 --gpu 2 --pt_name 'name_of_your_model_fold3_lang'
python main.py test --lang 'bi' --fold 4 --gpu 2 --pt_name 'name_of_your_model_fold4_lang'
python main.py test --lang 'bi' --fold 5 --gpu 2 --pt_name 'name_of_your_model_fold6_lang'

python main.py test --lang 'en' --fold 1 --gpu 2 --pt_name 'name_of_your_model_fold1_lang'
python main.py test --lang 'en' --fold 2 --gpu 2 --pt_name 'name_of_your_model_fold2_lang'
python main.py test --lang 'en' --fold 3 --gpu 2 --pt_name 'name_of_your_model_fold3_lang'
python main.py test --lang 'en' --fold 4 --gpu 2 --pt_name 'name_of_your_model_fold4_lang'
python main.py test --lang 'en' --fold 5 --gpu 2 --pt_name 'name_of_your_model_fold5_lang'

python main.py test --lang 'ko' --fold 1 --gpu 2 --pt_name 'name_of_your_model_fold1_lang'
python main.py test --lang 'ko' --fold 2 --gpu 2 --pt_name 'name_of_your_model_fold2_lang'
python main.py test --lang 'ko' --fold 3 --gpu 2 --pt_name 'name_of_your_model_fold3_lang'
python main.py test --lang 'ko' --fold 4 --gpu 2 --pt_name 'name_of_your_model_fold4_lang'
python main.py test --lang 'ko' --fold 5 --gpu 2 --pt_name 'name_of_your_model_fold5_lang'